name: Paper-Prefix
version: ${project.version}
main: eu.b1o.mc.paperprefix.PaperPrefix
api-version: 1.21
author: Julia, Link_1503, b1o.eu
description: A simple plugin to set player prefixes.
softdepend: [PlaceholderAPI]
commands:
  status:
    description: Sets your prefix.
    usage: /status <prefix>
  prefix:
    description: Sets your prefix.
    usage: /prefix <prefix>
